const dares = [
  "Envía un mensaje de voz cantando la canción que tienes en la cabeza.",
  "Publica 'soy una patata' en tu estado de WhatsApp.",
  "Envía una selfie haciendo una cara graciosa a este grupo.",
  "Imita a tu emoji favorito.",
  "Cuenta un chiste malo.",
  "Envía un audio diciendo 'soy el más divertido del grupo'.",
  "Escribe todo en mayúsculas por los próximos 5 minutos.",
  "Manda un mensaje de amor a la última persona que te escribió por privado.",
  "Escribe una historia corta usando solo emojis.",
  "Actúa como un robot durante 1 minuto.",
  "Habla sin usar la letra 'a' por los próximos 2 mensajes.",
  "Envía una foto de lo primero que ves a tu izquierda.",
  "Imita la voz de un personaje de caricatura en un audio.",
  "Di 'me gusta comer papas crudas' en un audio con tono serio.",
  "Envía un sticker que te represente en este momento.",
  "Manda un mensaje con solo letras aleatorias.",
  "Envía un audio diciendo un trabalenguas sin equivocarte.",
  "Haz una confesión vergonzosa.",
  "Envía una foto de tu calzado actual.",
  "Envía un meme que siempre te haga reír.",
  "Imita a un gato durante 10 segundos.",
  "Di tu color favorito en tono de película dramática.",
  "Describe tu día usando solo tres palabras.",
  "Envía una foto vieja tuya.",
  "Menciona a alguien y dile un cumplido exagerado.",
  "Imita a un profesor famoso que hayas tenido.",
  "Escribe una palabra inventada y dale significado.",
  "Envía un mensaje a un contacto aleatorio diciendo 'te soñé anoche'.",
  "Manda un sticker en cada mensaje por los próximos 2 minutos.",
  "Envía una captura de tu fondo de pantalla actual.",
  "Di el nombre de tu crush (o inventa uno si no tienes).",
  "Escribe un poema corto sobre el grupo.",
  "Haz una rima con el nombre de la persona que te habló último.",
  "Envía un audio diciendo 'soy el alma de la fiesta'.",
  "Imita a alguien del grupo sin decir quién es.",
  "Manda tu emoji más usado y explica por qué lo usas tanto.",
  "Haz una declaración falsa sobre ti, y que adivinen si es verdad o mentira.",
  "Cambia tu nombre en WhatsApp por algo gracioso durante una hora.",
  "Escribe una frase sin usar la letra 'e'.",
  "Envía un mensaje de voz diciendo el abecedario al revés.",
  "Describe tu película favorita como si fuera una receta de cocina.",
  "Haz una voz de narrador de documental describiendo lo que haces ahora.",
  "Envía una foto de tu mano.",
  "Actúa como si fueras un influencer por 15 segundos en un audio.",
  "Cambia tu foto de perfil por un meme por una hora.",
  "Di un secreto inofensivo.",
  "Haz una predicción sobre el futuro de alguien del grupo.",
  "Escribe una canción de amor de 2 líneas improvisada.",
  "Envía una frase motivacional absurda.",
  "Envía una foto de algo azul cerca de ti.",
  "Manda un mensaje diciendo 'me hackearon' sin contexto.",
  "Envía un audio diciendo 'soy el rey/la reina del drama'.",
  "Di el nombre de una comida que detestes.",
  "Imita una sirena de policía con tu voz.",
  "Haz una broma telefónica (real o simulada) en un audio.",
  "Envía una foto de lo que tienes en los bolsillos.",
  "Describe a la persona más habladora del grupo con una palabra.",
  "Haz un dibujo rápido y mándalo.",
  "Canta una parte de una canción popular actual.",
  "Envía un audio riéndote sin parar durante 10 segundos.",
  "Envía un mensaje en el grupo con solo emojis tristes.",
  "Di tu edad pero como si fuera un secreto clasificado.",
  "Imita a un famoso en un audio.",
  "Di 'te amo grupo' de forma dramática en un audio.",
  "Escribe el nombre de todos los del grupo que recuerdes.",
  "Envía una foto de lo último que comiste.",
  "Envía un meme que represente tu estado de ánimo.",
  "Envía tu palabra favorita y explica por qué.",
  "Haz una declaración épica como si fueras un héroe de película.",
  "Envía un audio riéndote como un villano.",
  "Haz una lista de 5 cosas que te hacen feliz.",
  "Envía un audio hablando como si fueras un locutor de radio.",
  "Escribe una frase sin espacios.",
  "Envía una foto de algo que empiece con la letra inicial de tu nombre.",
  "Haz una imitación del sonido de una gallina.",
  "Escribe una adivinanza inventada.",
  "Cambia tu descripción de WhatsApp por 'soy una leyenda viva' por 1 hora.",
  "Manda un saludo a alguien con una voz rara.",
  "Actúa como si fueras un youtuber saludando a tus fans.",
  "Envía un mensaje como si fueras un robot de servicio al cliente.",
  "Imita el sonido de tu animal favorito.",
  "Manda un 'buenos días' exageradamente alegre.",
  "Envía un audio diciendo el nombre del grupo con tono de telenovela.",
  "Haz un dibujo en Paint o a mano y mándalo.",
  "Di un dato curioso que pocos conozcan de ti.",
  "Imita el sonido de una alarma de despertador.",
  "Describe tu habitación con una sola palabra.",
  "Escribe algo completamente al revés.",
  "Cambia tu nombre en WhatsApp por 'El misterioso' durante una hora.",
  "Di algo bonito sobre la persona que mandó el mensaje antes que tú.",
  "Envía un mensaje actuando como si hubieras ganado la lotería.",
  "Envía un meme antiguo (de 2015 o antes).",
  "Escribe un mensaje sin usar la letra 'a'.",
  "Envía un video corto bailando (si te atreves 😏).",
  "Imita el sonido de un carro arrancando.",
  "Describe tu día como si fuera una película de terror.",
  "Haz una lista de tres deseos imposibles.",
  "Envía una selfie con cara seria.",
  "Envía un emoji que describa cómo te sientes sin explicarlo.",
  "Haz una confesión que nadie del grupo sepa.",
  "Escribe una frase como si fueras un pirata 🏴‍☠️.",
  "Di tres cosas sin las que no podrías vivir.",
  "Envía una foto de algo que huela bien.",
  "Escribe una mini historia en 10 palabras.",
  "Envía una frase de villano de película.",
  "Di 'soy el elegido' en un audio con tono épico."
];

const dareCommand = {
  name: "dare",
  category: "diversion",
  description: "Te da un 'Reto'.",
  aliases: ["reto"],

  async execute({ sock, msg }) {
    const randomDare = dares[Math.floor(Math.random() * dares.length)];
    await sock.sendMessage(msg.key.remoteJid, { text: `🎯 *Reto:* ${randomDare}` }, { quoted: msg });
  }
};

export default dareCommand;
