const questions = [
  "¿Ser invisible o poder volar?",
  "¿Vivir sin música o sin películas?",
  "¿Saber la fecha de tu muerte o la causa de tu muerte?",
  "¿Tener más tiempo o más dinero?",
  "¿Hablar todos los idiomas o poder hablar con los animales?",
  "¿Ser famoso pero pobre o desconocido pero rico?",
  "¿Nunca volver a dormir o dormir 20 horas al día?",
  "¿Poder leer la mente o controlar el tiempo?",
  "¿Viajar al pasado o al futuro?",
  "¿Comer solo pizza o solo hamburguesas toda tu vida?",
  "¿Vivir sin internet o sin amigos?",
  "¿Ser el más inteligente o el más atractivo?",
  "¿Perder todos tus recuerdos o no poder crear nuevos?",
  "¿Caminar descalzo sobre vidrios o sobre brasas?",
  "¿Ser un genio malvado o un héroe tonto?",
  "¿No poder mentir o que nadie te crea?",
  "¿Vivir en un mundo sin música o sin libros?",
  "¿Vivir en el espacio o bajo el mar?",
  "¿Ser un dragón o tener uno como mascota?",
  "¿Ser millonario por un año o tener dinero suficiente toda la vida?",
  "¿Poder parar el tiempo o retrocederlo unos segundos?",
  "¿Ser capaz de volar pero solo a 1 metro del suelo o correr a 200 km/h?",
  "¿Tener que cantar cada vez que hablas o bailar cada vez que caminas?",
  "¿No tener redes sociales o no tener celular?",
  "¿Ser un superhéroe sin poderes o un villano con poderes?",
  "¿Comer dulce por el resto de tu vida o solo salado?",
  "¿Vivir sin espejo o sin cámara?",
  "¿Ser inmortal o vivir 100 años perfectos?",
  "¿Vivir solo en una isla o en una ciudad superpoblada?",
  "¿Tener siempre hambre o siempre sueño?",
  "¿Perder el sentido del gusto o el del tacto?",
  "¿Ser un vampiro o un hombre lobo?",
  "¿Poder respirar bajo el agua o sobrevivir sin aire por una hora?",
  "¿Casarte con tu celebridad favorita o con tu mejor amigo/a?",
  "¿Nunca volver a usar ropa limpia o no poder ducharte?",
  "¿Tener que decir siempre la verdad o nunca hablar más?",
  "¿Vivir en el mundo de tu anime favorito o de tu videojuego favorito?",
  "¿Ser invencible físicamente o mentalmente?",
  "¿No poder reírte nunca más o reírte por todo?",
  "¿Olvidar a todos o que todos te olviden?",
  "¿Poder ver el futuro o cambiar el pasado?",
  "¿Ser el protagonista o el villano de tu historia?",
  "¿Ser un gato o un perro?",
  "¿Tener alas o tener una cola de dragón?",
  "¿Ser el más fuerte o el más rápido?",
  "¿Nunca tener frío o nunca tener calor?",
  "¿Vivir sin celular o sin televisión?",
  "¿Tener un millón hoy o ganar mil diarios por siempre?",
  "¿Vivir eternamente en invierno o en verano?",
  "¿Tener el poder de la telepatía o de la teletransportación?",
  "¿Comer algo que odias o no comer por un día?",
  "¿Vivir solo en el bosque o en una gran ciudad sin amigos?",
  "¿No poder usar internet o no poder bañarte?",
  "¿Ganar la lotería y perder a tus amigos o seguir igual toda la vida?",
  "¿Ser un mago poderoso o un guerrero legendario?",
  "¿Ser un hacker o un científico loco?",
  "¿Poder controlar el fuego o el agua?",
  "¿Hablar con los muertos o con los animales?",
  "¿Vivir tu peor día una y otra vez o no recordar tus mejores momentos?",
  "¿Tener una casa enorme o un auto de lujo?",
  "¿Ser famoso por algo tonto o desconocido por algo genial?",
  "¿Nunca envejecer o nunca enfermarte?",
  "¿Vivir en el pasado o en el futuro?",
  "¿Poder revivir a alguien o traer algo desaparecido?",
  "¿Vivir en un mundo sin amor o sin dinero?",
  "¿Ser siempre gracioso o siempre sabio?",
  "¿Tener el trabajo de tus sueños pero sin paga o uno aburrido con mucha paga?",
  "¿Poder teletransportarte o leer mentes?",
  "¿Ser un ángel o un demonio?",
  "¿Tener tres deseos o un millón de dólares?",
  "¿Dormir 5 minutos y sentirte descansado o dormir 10 horas sin descansar?",
  "¿Ser maestro o aprendiz para siempre?",
  "¿Vivir 10 vidas cortas o una larga?",
  "¿Ser olvidado o recordado por algo malo?",
  "¿Poder congelar el tiempo o adelantarlo?",
  "¿Ver en blanco y negro o no poder oír música?",
  "¿Comer todo lo que quieras sin engordar o dormir lo que quieras sin cansarte?",
  "¿Ser parte de Los Vengadores o de la Liga de la Justicia?",
  "¿Poder revivir tus sueños o entrar en los de otros?",
  "¿Ser pequeño como una hormiga o grande como un gigante?",
  "¿Vivir en un videojuego o en un anime?",
  "¿Viajar al espacio o al fondo del mar?",
  "¿Vivir solo un año de felicidad o 100 de tristeza?",
  "¿Ser el líder o el sabio del grupo?",
  "¿Cambiar tu pasado o conocer tu futuro?",
  "¿Tener memoria perfecta o olvidar lo que quieras?",
  "¿No poder parar de cantar o de bailar?",
  "¿Ser el mejor en algo que odias o malo en algo que amas?",
  "¿Poder manipular el clima o los sueños?",
  "¿Ser famoso en internet o en la vida real?",
  "¿Poder curar a otros o curarte siempre?",
  "¿Vivir en el mundo de Pokémon o de Naruto?",
  "¿Tener el poder del fuego o del hielo?",
  "¿Vivir sin miedo o sin dolor?",
  "¿Poder convertirte en cualquier animal o controlar a los animales?",
  "¿Tener éxito pero sin amor o amor sin éxito?",
  "¿Ganar siempre o nunca perder?",
  "¿Nunca dormir o nunca comer?",
  "¿Vivir como un rey por un año o como una persona normal toda la vida?",
  "¿Poder revivir un día feliz o borrar uno triste?",
  "¿Tener la voz más hermosa o la sonrisa más encantadora?",
  "¿Ser millonario pero solo o pobre pero amado?",
  "¿Cambiar el mundo o cambiar tu vida?",
  "¿Poder pausar la realidad o entrar en tus recuerdos?",
  "¿Ser un espíritu libre o un sabio inmortal?"
];

const wyrCommand = {
  name: "wouldyourather",
  category: "diversion",
  description: "Te da una pregunta de '¿Qué prefieres?'.",
  aliases: ["wyr", "queprefieres"],

  async execute({ sock, msg }) {
    const randomQuestion = questions[Math.floor(Math.random() * questions.length)];

    const decoraciones = [
      "💭✨🌸🌟",
      "🌈💬🎭💞",
      "💫🌻🧠🌙",
      "🎲🎯🌹🩵",
      "🌠💭🌷🧩"
    ];
    const deco = decoraciones[Math.floor(Math.random() * decoraciones.length)];

    const mensaje = `${deco}\n*💭 ¿Qué prefieres? 💭*\n${deco}\n\n${randomQuestion}\n\n🤔 Responde con tu elección 👇`;

    await sock.sendMessage(msg.key.remoteJid, { text: mensaje }, { quoted: msg });
  }
};

export default wyrCommand;
